// ============================================================
// AksesPangan — Server Memory Data Store for Microservices
// ============================================================

import type { User, SurplusItem, Booking, Notification, ImpactData, ImpactTimeline } from '@/types';
import { CO2E_FACTOR, TREE_CO2_ABSORPTION } from './constants';

interface ServerState {
  users: User[];
  surplusItems: SurplusItem[];
  bookings: Booking[];
  notifications: Notification[];
  initialized: boolean;
}

// Global singleton to persist across Next.js API route invocations
declare global {
  // eslint-disable-next-line no-var
  var __aksespangan_server_store__: ServerState | undefined;
}

function getInitialServerState(): ServerState {
  const users: User[] = [
    {
      id: 'admin-1',
      name: 'Admin AksesPangan',
      email: 'admin@aksespangan.id',
      password: 'admin',
      role: 'admin',
      phone: '081234567890',
      createdAt: '2025-01-01T00:00:00.000Z',
    },
    {
      id: 'penyedia-1',
      name: 'Ahmad Fauzi',
      email: 'ahmad@restoran.com',
      password: 'password123',
      role: 'penyedia',
      phone: '081298765432',
      businessName: 'Restoran Minang Jaya',
      businessAddress: 'Jl. Sudirman No. 45, Jakarta Pusat',
      businessType: 'restoran',
      location: { lat: -6.2088, lng: 106.8456 },
      createdAt: '2025-01-10T00:00:00.000Z',
    },
    {
      id: 'penyedia-2',
      name: 'Budi Santoso',
      email: 'budi@bakery.com',
      password: 'password123',
      role: 'penyedia',
      phone: '081311223344',
      businessName: 'Bakery Makmur',
      businessAddress: 'Jl. Thamrin No. 12, Jakarta Pusat',
      businessType: 'kafe',
      location: { lat: -6.195, lng: 106.823 },
      createdAt: '2025-01-12T00:00:00.000Z',
    },
    {
      id: 'penerima-1',
      name: 'Rina Wulandari',
      email: 'rina@gmail.com',
      password: 'password123',
      role: 'penerima',
      phone: '082112345678',
      location: { lat: -6.21, lng: 106.84 },
      createdAt: '2025-01-15T00:00:00.000Z',
    },
    {
      id: 'penerima-2',
      name: 'Yoga Pratama',
      email: 'yoga@gmail.com',
      password: 'password123',
      role: 'penerima',
      phone: '082198765432',
      location: { lat: -6.22, lng: 106.83 },
      createdAt: '2025-01-18T00:00:00.000Z',
    },
  ];

  const surplusItems: SurplusItem[] = [
    // --- Bandung & Bojongsoang Area (User Neighborhood) ---
    {
      id: 'surplus-bdg-1',
      providerId: 'penyedia-bdg-1',
      providerName: 'Siti Rohani',
      providerBusinessName: 'Dapur Sunda Bojongsoang',
      name: 'Nasi Liwet Komplit Ayam Bakar',
      description: 'Nasi liwet wangi kasturi, ayam bakar bumbu rujak, tahu tempe goreng, lalapan segar dan sambal terasi khas priangan.',
      photo: '/images/surplus-nasi-liwet.jpg',
      quantity: 6,
      portionCount: 15,
      productionTime: new Date(Date.now() - 2 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 4 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'nasi',
      location: { lat: -6.9712, lng: 107.6335 },
      address: 'Jl. Raya Bojongsoang No. 65, Bojongsoang',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-2',
      providerId: 'penyedia-bdg-2',
      providerName: 'Ahmad Dahlan',
      providerBusinessName: 'RM Minang Raya Buahbatu',
      name: 'Nasi Padang Rendang & Gulai Ayam',
      description: 'Paket nasi padang lengkap lauk rendang sapi empuk, gulai ayam, sayur nangka, dan sambal hijau segar.',
      photo: '/images/surplus-nasi-padang.jpg',
      quantity: 5,
      portionCount: 12,
      productionTime: new Date(Date.now() - 3 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 3.5 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'nasi',
      location: { lat: -6.9530, lng: 107.6320 },
      address: 'Jl. Buahbatu No. 182, Buahbatu, Bandung',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-3',
      providerId: 'penyedia-bdg-3',
      providerName: 'Dian Permata',
      providerBusinessName: 'Katering Mitra Batununggal',
      name: 'Nasi Bento Katering Seminar',
      description: 'Nasi bento higienis isi ayam teriyaki, egg roll, salad mayones, dan nasi pulen sisa pesanan seminar.',
      photo: '/images/surplus-nasi-bento.jpg',
      quantity: 4,
      portionCount: 10,
      productionTime: new Date(Date.now() - 1.5 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 5 * 3600000).toISOString(),
      status: 'active',
      price: 8000,
      isFree: false,
      foodCategory: 'nasi',
      location: { lat: -6.9580, lng: 107.6340 },
      address: 'Jl. Batununggal Indah No. 12, Batununggal',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-4',
      providerId: 'penyedia-bdg-4',
      providerName: 'Kang Cecep',
      providerBusinessName: 'Dapur Lengkong Tradisional',
      name: 'Paket Nasi Timbel Komplit',
      description: 'Nasi timbel daun pisang, ayam goreng lengkuas, gepuk daging sapi, tahu tempe dan sambal dadak.',
      photo: '/images/surplus-nasi-timbel.jpg',
      quantity: 7,
      portionCount: 18,
      productionTime: new Date(Date.now() - 2.5 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 3 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'nasi',
      location: { lat: -6.9385, lng: 107.6210 },
      address: 'Jl. Lengkong Besar No. 40, Lengkong',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-5',
      providerId: 'penyedia-bdg-5',
      providerName: 'Habib Umar',
      providerBusinessName: 'Resto Timur Tengah Dayeuhkolot',
      name: 'Nasi Kebuli Daging Kambing',
      description: 'Nasi kebuli rempah arabian dengan potongan daging kambing empuk, acar nanas, dan kerupuk emping.',
      photo: '/images/surplus-nasi-kebuli.jpg',
      quantity: 5,
      portionCount: 14,
      productionTime: new Date(Date.now() - 4 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 4 * 3600000).toISOString(),
      status: 'active',
      price: 10000,
      isFree: false,
      foodCategory: 'nasi',
      location: { lat: -6.9830, lng: 107.6245 },
      address: 'Jl. Raya Dayeuhkolot No. 88, Dayeuhkolot',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-6',
      providerId: 'penyedia-bdg-6',
      providerName: 'Jeanne Marie',
      providerBusinessName: 'Artisan Bakery Buahbatu',
      name: 'Aneka Roti Manis & Butter Croissant',
      description: 'Croissant mentega Perancis, roti sobek cokelat, danish buah berry. Dipanggang pagi ini, masih renyah.',
      photo: '/images/surplus-bakery.jpg',
      quantity: 3,
      portionCount: 15,
      productionTime: new Date(Date.now() - 5 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 6 * 3600000).toISOString(),
      status: 'active',
      price: 5000,
      isFree: false,
      foodCategory: 'roti',
      location: { lat: -6.9460, lng: 107.6290 },
      address: 'Jl. Buahbatu No. 90, Buahbatu, Bandung',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-7',
      providerId: 'penyedia-bdg-7',
      providerName: 'Ratna Sari',
      providerBusinessName: 'Bakery Sourdough Bojongsoang',
      name: 'Roti Sourdough & Baguette Organik',
      description: 'Artisan rustic sourdough loaf dan baguette gandum organik tanpa pengawet. Sangat bergizi.',
      photo: '/images/surplus-sourdough.jpg',
      quantity: 3,
      portionCount: 10,
      productionTime: new Date(Date.now() - 4 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 7 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'roti',
      location: { lat: -6.9685, lng: 107.6360 },
      address: 'Jl. Raya Bojongsoang No. 112, Bojongsoang',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-8',
      providerId: 'penyedia-bdg-8',
      providerName: 'Hendra Gunawan',
      providerBusinessName: 'Resto Sehat Alami Batununggal',
      name: 'Capcay Seafood & Tahu Organik',
      description: 'Capcay sayur kuah kental dengan udang, bakso ikan, brokoli, wortel manis, dan tahu sutra organik.',
      photo: '/images/surplus-capcay.jpg',
      quantity: 4,
      portionCount: 12,
      productionTime: new Date(Date.now() - 2 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 4 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'sayur',
      location: { lat: -6.9560, lng: 107.6280 },
      address: 'Jl. Batununggal Indah IV No. 18, Bandung',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-9',
      providerId: 'penyedia-bdg-9',
      providerName: 'Pak Dedi',
      providerBusinessName: 'Kios Sayur Mitra Ciganitri',
      name: 'Paket Sayuran Segar Lembang',
      description: 'Buncis, wortel organik, sawi putih, dan tomat merah segar panenan kebun mitra Lembang.',
      photo: '/images/surplus-produce.jpg',
      quantity: 6,
      portionCount: 16,
      productionTime: new Date(Date.now() - 6 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 8 * 3600000).toISOString(),
      status: 'active',
      price: 4000,
      isFree: false,
      foodCategory: 'sayur',
      location: { lat: -6.9765, lng: 107.6405 },
      address: 'Jl. Ciganitri No. 25, Bojongsoang',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-10',
      providerId: 'penyedia-bdg-10',
      providerName: 'Ibu Ningsih',
      providerBusinessName: 'Kios Buah Berkah Bojongsoang',
      name: 'Semangka & Melon Potong Higienis',
      description: 'Semangka merah tanpa biji dan melon madu manis potongan segar dalam kotak food-grade tertutup.',
      photo: '/images/surplus-buah-potong.jpg',
      quantity: 5,
      portionCount: 15,
      productionTime: new Date(Date.now() - 1 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 6 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'buah',
      location: { lat: -6.9730, lng: 107.6310 },
      address: 'Jl. Raya Bojongsoang No. 34, Bojongsoang',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-11',
      providerId: 'penyedia-bdg-11',
      providerName: 'Kopi Seduh Team',
      providerBusinessName: 'Kafe Kopi Seduh Lengkong',
      name: 'Cold Brew Botanical Tea & Coffee',
      description: 'Cold brew tea melati dan kopi cold brew arabika single origin dalam botol kaca 350ml steril.',
      photo: '/images/surplus-beverage.jpg',
      quantity: 3,
      portionCount: 8,
      productionTime: new Date(Date.now() - 3 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 9 * 3600000).toISOString(),
      status: 'active',
      price: 5000,
      isFree: false,
      foodCategory: 'minuman',
      location: { lat: -6.9340, lng: 107.6190 },
      address: 'Jl. Lengkong Kecil No. 22, Lengkong, Bandung',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-bdg-12',
      providerId: 'penyedia-bdg-12',
      providerName: 'Ibu Eni',
      providerBusinessName: 'Kedai Segar Bojongsoang',
      name: 'Jus Jeruk Peras & Alpukat Murni',
      description: 'Jus jeruk peras murni tanpa gula pasir dan jus alpukat mentega segar dingin kemasan botol.',
      photo: '/images/surplus-juice.jpg',
      quantity: 3,
      portionCount: 10,
      productionTime: new Date(Date.now() - 2 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 5 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'minuman',
      location: { lat: -6.9695, lng: 107.6350 },
      address: 'Jl. Raya Bojongsoang No. 78, Bojongsoang',
      createdAt: new Date().toISOString(),
    },
    // --- Jakarta Area Items ---
    {
      id: 'surplus-jkt-1',
      providerId: 'penyedia-1',
      providerName: 'Ahmad Fauzi',
      providerBusinessName: 'Restoran Minang Jaya',
      name: 'Nasi Padang Sisa Catering',
      description: 'Lauk ayam bakar, rendang, sayur nangka, sambal ijo. Dikemas higienis dalam box makanan.',
      photo: '/images/surplus-nasi-padang.jpg',
      quantity: 5,
      portionCount: 10,
      productionTime: new Date(Date.now() - 2 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 4 * 3600000).toISOString(),
      status: 'active',
      price: 0,
      isFree: true,
      foodCategory: 'nasi',
      location: { lat: -6.2088, lng: 106.8456 },
      address: 'Jl. Sudirman No. 45, Jakarta Pusat',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'surplus-jkt-2',
      providerId: 'penyedia-2',
      providerName: 'Budi Santoso',
      providerBusinessName: 'Bakery Makmur',
      name: 'Aneka Roti Manis & Croissant',
      description: 'Roti coklat, keju, dan croissant sisa display hari ini. Masih empuk dan harum.',
      photo: '/images/surplus-bakery.jpg',
      quantity: 3,
      portionCount: 15,
      productionTime: new Date(Date.now() - 6 * 3600000).toISOString(),
      expiryTime: new Date(Date.now() + 8 * 3600000).toISOString(),
      status: 'active',
      price: 5000,
      isFree: false,
      foodCategory: 'roti',
      location: { lat: -6.195, lng: 106.823 },
      address: 'Jl. Thamrin No. 12, Jakarta Pusat',
      createdAt: new Date().toISOString(),
    },
  ];

  const bookings: Booking[] = [
    {
      id: 'booking-hist-1',
      surplusId: 'surplus-hist-1',
      surplusName: 'Nasi Box Rendang & Telur',
      surplusPhoto: '',
      providerId: 'penyedia-1',
      providerBusinessName: 'Restoran Minang Jaya',
      recipientId: 'penerima-1',
      recipientName: 'Rina Wulandari',
      recipientPhone: '082112345678',
      quantity: 5,
      status: 'diambil',
      bookedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      confirmedAt: new Date(Date.now() - 7 * 86400000 + 1800000).toISOString(),
      pickedUpAt: new Date(Date.now() - 7 * 86400000 + 3600000).toISOString(),
      pickupDeadline: new Date(Date.now() - 7 * 86400000 + 7200000).toISOString(),
      pickupLocation: { lat: -6.2088, lng: 106.8456 },
      pickupAddress: 'Jl. Sudirman No. 45',
    },
  ];

  return {
    users,
    surplusItems,
    bookings,
    notifications: [],
    initialized: true,
  };
}

export function getServerStore(): ServerState {
  const needsUpdate =
    !global.__aksespangan_server_store__ ||
    !global.__aksespangan_server_store__.surplusItems.some((i) => i.id.startsWith('surplus-bdg')) ||
    !global.__aksespangan_server_store__.surplusItems.some((i) => i.id === 'surplus-bdg-2' && i.photo === '/images/surplus-nasi-padang.jpg');

  if (needsUpdate) {
    global.__aksespangan_server_store__ = getInitialServerState();
  }
  return global.__aksespangan_server_store__!;
}

export function calculateServerImpact(): ImpactData {
  const store = getServerStore();
  const completed = store.bookings.filter((b) => b.status === 'diambil');
  const totalKg = completed.reduce((sum, b) => sum + b.quantity, 0) + 125;
  const totalPortions = Math.round(totalKg * 2.5);
  const totalCO2e = Math.round(totalKg * CO2E_FACTOR * 10) / 10;
  const totalTransactions = completed.length + 42;
  const providers = new Set(store.users.filter((u) => u.role === 'penyedia').map((u) => u.id));
  const recipients = new Set(store.users.filter((u) => u.role === 'penerima').map((u) => u.id));

  return {
    totalKgSaved: totalKg,
    totalPortions,
    totalCO2eSaved: totalCO2e,
    totalTransactions,
    totalProviders: Math.max(providers.size, 18),
    totalRecipients: Math.max(recipients.size, 156),
    treeEquivalent: Math.round((totalCO2e / TREE_CO2_ABSORPTION) * 10) / 10,
  };
}
